## 1. Arithmetic Operations with NumPy
NumPy arrays provide a variety of functions to perform arithmetic
operations.

### 1.1 Finding Square Roots
The sqrt() function is used to find the square roots of all the elements in a
list

In [3]:
# Import the numpy library and give it the alias 'np' for easy access
import numpy as np

# Define a list of numbers
nums = [10, 20, 30, 40, 50]

# Use numpy's sqrt function to compute the square root of each element in the list
# Note: np.sqrt automatically converts the list to a numpy array
np_sqr = np.sqrt(nums)

# Print the resulting numpy array of square roots
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


### 1.2. Finding Logs
The log() function is used to find the logs of all the elements in a list

In [5]:
# Define a list of numbers
nums = [10, 20, 30, 40, 50]

# Compute the natural logarithm (base e) of each element in the list using numpy's log function
np_log = np.log(nums)

# Print the resulting array of natural logarithms
print(np_log)


[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


### 1.3. Finding Exponents
The exp() function takes the exponents of all the elements in a list

In [7]:
# Define a Python list of numbers
nums = [10, 20, 30, 40, 50]

# Compute the exponential (e^x) of each number in the list
# np.exp applies the exponential function element-wise to the array
np_exp = np.exp(nums)

# Print the resulting numpy array of exponentials
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


### 1.4. Finding Sine and Cosine
You can find the sines and cosines of items in a list using the sine and cosine
function, respectively

In [8]:
# Create a Python list of numbers
nums = [10, 20, 30, 40, 50]

# Apply the numpy sine function to each element in the list
# np.sin expects the input in radians, so these values will be treated as radians
np_sine = np.sin(nums)

# Print the resulting array of sine values
print(np_sine)

# Reset the nums list (not necessary here since it hasn't changed)
nums = [10, 20, 30, 40, 50]

# Apply the numpy cosine function to each element in the list
# np.cos also expects the input in radians
np_cos = np.cos(nums)

# Print the resulting array of cosine values
print(np_cos)


[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


## 2. NumPy for Linear Algebra Operations
Data science makes extensive use of linear algebra. The support for
performing advanced linear algebra functions quickly and efficiently makes
NumPy one of the most routinely used libraries for data science. In this
section, you will perform some of the most linear algebraic operations with
NumPy.

### 2.1. Finding the Matrix Dot Product
To find a matrix dot product, you can use the dot() function. To find the dot
product, the number of columns in the first matrix must match the number of
rows in the second matrix.

In [9]:
# Create a 4x5 matrix (4 rows, 5 columns) filled with random numbers from a standard normal distribution
A = np.random.randn(4, 5)

# Create a 5x4 matrix (5 rows, 4 columns) filled with random numbers from a standard normal distribution
B = np.random.randn(5, 4)

# Compute the dot product (matrix multiplication) of A and B
# The result Z will be a 4x4 matrix because (4x5) • (5x4) = (4x4)
Z = np.dot(A, B)

# Print the resulting 4x4 matrix
print(Z)


[[-2.4649127   3.37438331 -0.53709299  1.14242599]
 [-3.72465358  2.17270064 -0.30247285  1.0346814 ]
 [-1.88389333 -1.26145002  0.8108699  -1.17992989]
 [ 1.71057131  0.42784236  1.47044998  2.02463457]]


### 2.2. Element-wise Matrix Multiplication
In addition to finding the dot product of two matrices, you can element-wise
multiply two matrices. To do so, you can use the multiply() function.

In [10]:
# Define three rows as Python lists
row1 = [10, 12, 13]  # First row of numbers
row2 = [45, 32, 16]  # Second row of numbers
row3 = [45, 32, 16]  # Third row of numbers

# Create a 2D NumPy array from the three rows
nums_2d = np.array([row1, row2, row3])

# Perform element-wise multiplication of the array with itself
# This squares each element in the 2D array
multiply = np.multiply(nums_2d, nums_2d)

# Print the resulting 2D array where each element is squared
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


### 2.3. Finding the Matrix Inverse
You find the inverse of a matrix via the linalg.inv() function

In [11]:
# Define three rows as Python lists
row1 = [1, 2, 3]
row2 = [5, 2, 8]
row3 = [9, 1, 10]

# Create a 2D NumPy array (matrix) from the three rows
nums_2d = np.array([row1, row2, row3])

# Compute the inverse of the 2D matrix using NumPy's linear algebra module
inverse = np.linalg.inv(nums_2d)

# Print the inverse matrix
print(inverse)


[[ 0.70588235 -1.          0.58823529]
 [ 1.29411765 -1.          0.41176471]
 [-0.76470588  1.         -0.47058824]]


### 2.4. Finding the Matrix Determinant
The determinant of a matrix can be found using the linalg.det() function

In [12]:
# Define three lists, each representing a row of a 3x3 matrix
row1 = [1, 2, 3]     # First row of the matrix
row2 = [5, 2, 8]     # Second row of the matrix
row3 = [9, 1, 10]    # Third row of the matrix

# Create a 2D NumPy array (matrix) from the three rows
nums_2d = np.array([row1, row2, row3])

# Compute the determinant of the matrix using NumPy's linear algebra module
determinant = np.linalg.det(nums_2d)

# Print the determinant of the matrix
print(determinant)

16.999999999999993


### 2.5. Finding the Matrix Trace
The trace of a matrix refers to the sum of all the elements along the diagonal
of a matrix. To find the trace of a matrix, you can use the trace() function

In [13]:
# Define three rows of numbers as Python lists
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

# Create a 2D NumPy array (matrix) from the three rows
nums_2d = np.array([row1, row2, row3])

# Calculate the trace of the matrix (sum of diagonal elements: 1 + 5 + 9)
trace = np.trace(nums_2d)

# Print the result (should output 15)
print(trace)


15


### 2.6. Solving a System of Linear Equations with Python
Now that you know how to use the NumPy library to perform various linear
algebra functions, let’s try to solve a system of linear equations, which is one
of the most basic problems in linear algebra.
A system of linear equations refers to a collection of equations with some
unknown variables. Solving a system of linear equations refers to finding the
values of the unknown variables in equations. One of the ways to solve a
system of linear equations is via matrices.

In [14]:
# Define a 2x2 matrix A
A = np.array([[6, 3], 
              [2, 4]])

# Define a 1D array (vector) B
B = np.array([42, 32])

# Calculate the inverse of matrix A using NumPy's linear algebra module
A_inv = np.linalg.inv(A)

# Print the inverse of A
print(A_inv)

# Solve for X in the equation A * X = B by multiplying A_inv and B
# This is equivalent to X = A⁻¹ * B
X = np.dot(A_inv, B)

# Print the solution vector X
print(X)


[[ 0.22222222 -0.16666667]
 [-0.11111111  0.33333333]]
[4. 6.]
