## 1. Introduction to NumPy Arrays

The main data structure in the NumPy library is the NumPy array, which is
an extremely fast and memory-efficient data structure. The NumPy array is
much faster than the common Python list and provides vectorized matrix
operations.

## 2. Numpy Data Types
The NumPy library supports all the default Python data types in addition to
some of its intrinsic data types. This means that the default Python data types,
e.g., strings, integers, floats, Booleans, and complex data types, can be stored
in NumPy arrays.

In [4]:
# Import the NumPy library and give it the alias 'np'
import numpy as np

In [5]:
# Create a NumPy array with the given list of integers
my_array = np.array([10, 12, 14, 16, 20, 25])

# Print the entire array
print(my_array)  # Output: [10 12 14 16 20 25]

# Print the data type of the elements in the array
print(my_array.dtype)  # Output: dtype of the array elements (e.g., int32 or int64)

# Print the size in bytes of each element in the array
print(my_array.dtype.itemsize)  # Output: number of bytes used by each element (4 bytes)

[10 12 14 16 20 25]
int32
4


In [7]:
# Create a NumPy array with three string elements
my_array = np.array(["Red", "Green", "Orange"])

# Print the contents of the array
print(my_array)

# Print the data type of the elements in the array
# Since it's a string array, dtype will show a Unicode string type like <U6 (max 6 characters)
print(my_array.dtype)

# Print the size in bytes of each element in the array
# This shows how many bytes each element occupies in memory
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [9]:
# Create a NumPy array of strings (each string is a date in YYYY-MM-DD format)
my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])

# Print the contents of the array
print(my_array)  # Output: ['1990-10-04' '1989-05-06' '1990-11-04']

# Print the data type of the array elements
print(my_array.dtype)  # Output: <U10 (Unicode string of max length 10)

# Print the size in bytes of each item in the array
print(my_array.dtype.itemsize)  # Output: 40 (since each Unicode character is 4 bytes and max length is 10 -> 10*4)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [12]:
# Convert the data type of the existing NumPy array (my_array) to datetime64 with default unit (nanoseconds)
# The "M" means datetime64 in NumPy (it can store dates and times)
my_array3 = my_array.astype("M")

# Print the data type of the new array (should show datetime64[ns] or similar)
print(my_array3.dtype)

# Print the size in bytes of each element in the new array
# datetime64 elements typically use 8 bytes (64 bits)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [15]:
# Create a NumPy array of date strings and specify dtype="M" (datetime64)
my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"], dtype="M")

# Print the array; it will display as NumPy datetime64 objects
print(my_array)

# Print the data type of the array elements (should be datetime64[D])
print(my_array.dtype)

# Print the size in bytes of one array element (datetime64[D] typically uses 8 bytes)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
datetime64[D]
8


## 3. Creating NumPy Arrays
Depending on the type of data you need inside your NumPy array, different
methods can be used to create a NumPy array.

### 3.1 Using Array Method
To create a NumPy array, you can pass a list to the array() method of the NumPy module.

In [19]:
# Define a Python list with some integer values
nums_list = [10, 12, 14, 16, 20]

# Convert the Python list into a NumPy array
nums_array = np.array(nums_list)

# Check and display the type of nums_array (should be <class 'numpy.ndarray'>)
type(nums_array)

numpy.ndarray

In [21]:
# Define three lists representing rows of a 2D array
row1 = [10, 12, 13]  # First row with three elements
row2 = [45, 32, 16]  # Second row with three elements
row3 = [45, 32, 16]  # Third row with three elements (same as row2)

# Create a 2D NumPy array (matrix) from the three rows
nums_2d = np.array([row1, row2, row3])

# Get the shape of the 2D array
# This returns a tuple (number_of_rows, number_of_columns)
nums_2d.shape  # Output: (3, 3) because there are 3 rows and 3 columns

(3, 3)

### 3.2 Using Arrange Method
With the arrange () method, you can create a NumPy array that contains a
range of integers. The first parameter to the arrange method is the lower
bound, and the second parameter is the upper bound. The lower bound is
included in the array. However, the upper bound is not included.

In [23]:
# Create a NumPy array with values starting from 5 up to (but not including) 11
nums_arr = np.arange(5, 11)  

# Print the created NumPy array
print(nums_arr)

[ 5  6  7  8  9 10]


In [25]:
# Create a NumPy array with values starting from 5 up to (but not including) 12, with a step size of 2
nums_arr = np.arange(5, 12, 2)

# Print the resulting array to the console
print(nums_arr)

[ 5  7  9 11]


### 3.3 Using Ones Method
The ones() method can be used to create a NumPy array of all ones.

In [26]:
# Create a NumPy array of size 6 where all elements are 1.0 (default dtype is float)
ones_array = np.ones(6)

# Print the created array to the console
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [27]:
# Create a 6x4 array filled with ones
ones_array = np.ones((6, 4))

# Print the array to the console
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 3.4 Using Zeros Method
The zeros() method can be used to create a NumPy array of all zeros.

In [29]:
# Create a NumPy array of length 6 filled with zeros
zeros_array = np.zeros(6)

# Print the array to the console
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [30]:
# Create a 2D NumPy array (matrix) of shape (6, 4) filled with zeros
zeros_array = np.zeros((6, 4))

# Print the array to the console
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 3.5 Using Eyes Method
The eye() method is used to create an identity matrix in the form of a twodimensional
NumPy array. An identity matrix contains 1s along the diagonal,
while the rest of the elements are 0 in the array.

In [31]:
# Create a 5x5 identity matrix using np.eye()
# An identity matrix has 1's on the diagonal and 0's elsewhere
eyes_array = np.eye(5)

# Print the resulting 5x5 identity matrix to the console
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 3.6 Using Random Method
The random.rand() function from the NumPy module can be used to create
a NumPy array with uniform distribution.

In [33]:
# Generate a 4x5 array of random numbers uniformly distributed between 0 and 1
uniform_random = np.random.rand(4, 5)

# Print the generated 4x5 array to the console
print(uniform_random)

[[0.62987708 0.64049863 0.38782618 0.93707607 0.47108732]
 [0.68870667 0.69878135 0.34268919 0.67006862 0.98412537]
 [0.96124806 0.87254572 0.15566187 0.4900693  0.80279346]
 [0.95050039 0.50218701 0.76270319 0.39453532 0.8847946 ]]


In [34]:
# Generate a 4x5 array (4 rows, 5 columns) of random numbers
# Each number is drawn from a standard normal distribution (mean = 0, std dev = 1)
normal_random = np.random.randn(4, 5)

# Print the generated 4x5 array of random numbers
print(normal_random)

[[ 0.80499536  2.54836929 -0.45601348  0.42304521 -1.26984654]
 [ 0.74009432  1.4857653   0.12907637 -0.44859458 -0.34207067]
 [ 0.32943771  0.15232069  0.96790114 -2.40587923  0.68016379]
 [ 1.18145413 -0.72025265 -0.23976155  0.81708831 -0.64636418]]


In [35]:
# Generate an array of 5 random integers between 10 (inclusive) and 50 (exclusive)
integer_random = np.random.randint(10, 50, 5)

# Print the array of random integers
print(integer_random)

[33 27 48 19 43]


## 4. Printing NumPy Arrays
Depending on the dimensions, there are various ways to display the NumPy
arrays.
The simplest way to print a NumPy array is to pass the array to the print
method

In [37]:
# Create a NumPy array with the elements 10, 12, 14, 16, 20, and 25
my_array = np.array([10, 12, 14, 16, 20, 25])

# Print the contents of the array to the console
print(my_array)

[10 12 14 16 20 25]


In [38]:
# Print the number of dimensions (axes) of the NumPy array
print(my_array.ndim)

# Print the shape of the NumPy array as a tuple (size along each dimension)
print(my_array.shape)

1
(6,)


In [39]:
# Loop over each element in the NumPy array 'my_array'
for i in my_array:
    # Print the current element 'i'
    print(i)

10
12
14
16
20
25


In [40]:
# Generate a 4x5 array of random integers between 1 and 10 (inclusive)
# np.random.randint(low, high, size) generates random integers from low (inclusive) to high (exclusive)
# Here, 1 is inclusive, 11 is exclusive (so values are from 1 to 10)
integer_random = np.random.randint(1, 11, size=(4, 5))

# Print the generated 4x5 array of random integers
print(integer_random)

[[5 3 2 1 4]
 [5 6 9 5 6]
 [6 3 4 5 6]
 [9 9 7 6 4]]


In [41]:
# Print the number of dimensions (axes) of the NumPy array 'integer_random'
print(integer_random.ndim)

# Print the shape of the NumPy array 'integer_random' as a tuple (size along each dimension)
print(integer_random.shape)

2
(4, 5)


In [43]:
# Iterate over each element in the NumPy array `integer_random`
for i in integer_random:
    # Print the current element `i`
    print(i)

[5 3 2 1 4]
[5 6 9 5 6]
[6 3 4 5 6]
[9 9 7 6 4]


In [44]:
# Loop through each row in the 2D NumPy array `integer_random`
for rows in integer_random:
    # Loop through each element (column) in the current row
    for column in rows:
        # Print the current element (column value)
        print(column)

5
3
2
1
4
5
6
9
5
6
6
3
4
5
6
9
9
7
6
4


## 5. Adding Items in a NumPy Array
To add the items into a NumPy array, you can use the append() method from
the NumPy module. First, you need to pass the original array and the item
that you want to append to the array to the append() method. The append()
method returns a new array that contains newly added items appended to the
end of the original array.

In [45]:
# Create a NumPy array with three string elements: "Red", "Green", and "Orange"
my_array = np.array(["Red", "Green", "Orange"])

# Print the original array
print(my_array)

# Use np.append() to add the string "Yellow" to the end of the array
# Note: np.append() does not modify the original array; it returns a new array
extended = np.append(my_array, "Yellow")

# Print the new array that includes the appended element
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow']


In [46]:
# Create a NumPy array with three string elements: "Red", "Green", and "Orange"
my_array = np.array(["Red", "Green", "Orange"])

# Print the original array
print(my_array)  # Output: ['Red' 'Green' 'Orange']

# Use np.append to add two more elements "Yellow" and "Pink" to the original array
# Note: np.append does not modify the original array; it returns a new extended array
extended = np.append(my_array, ["Yellow", "Pink"])

# Print the new extended array
print(extended)  # Output: ['Red' 'Green' 'Orange' 'Yellow' 'Pink']

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow' 'Pink']


In [47]:
# Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))

# Print the 3x3 array of zeros to the console
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
# Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))

# Print the original 3x3 array of zeros
print(zeros_array)

print("Extended Array")

# Append a new row [1, 2, 3] to the original array along axis 0 (rows)
# axis=0 means we are adding the new row at the bottom of the existing array
extended = np.append(zeros_array, [[1, 2, 3]], axis=0)

# Print the extended array which now has 4 rows (the original 3 plus the new row)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


In [49]:
# Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))  
print(zeros_array)  # Print the original 3x3 zeros array

print("Extended Array")  # Print a label to indicate the next output is the extended array

# Append a new column [[1], [2], [3]] to the original array along axis 1 (columns)
# The new column has 3 rows and 1 column, matching the number of rows in zeros_array
extended = np.append(zeros_array, [[1], [2], [3]], axis=1)

print(extended)  # Print the resulting 3x4 array after appending

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


## 6. Removing Items from a NumPy Array
To delete an item from an array, you may use the delete() method. You need
to pass the existing array and the index of the item to be deleted to the
delete() method.

In [51]:
# Create a NumPy array with string elements
my_array = np.array(["Red", "Green", "Orange"])

# Print the original array
print(my_array)

# Print a message to indicate the next output is after deletion
print("After deletion")

# Delete the element at index 1 ("Green") from the array
# np.delete(array, index) returns a new array with the specified index removed
updated_array = np.delete(my_array, 1)

# Print the updated array after deletion
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red' 'Orange']


In [52]:
# Create a NumPy array containing three string elements
my_array = np.array(["Red", "Green", "Orange"])

# Print the original array
print(my_array)

# Print a message indicating that deletion will occur
print("After deletion")

# Delete elements at index positions 1 and 2 ('Green' and 'Orange') from the array
# np.delete(array, [indices]) removes elements at the specified indices
updated_array = np.delete(my_array, [1, 2])

# Print the updated array after deletion
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red']


In [53]:
# Generate a 2D NumPy array of random integers
# np.random.randint(1, 11, size=(4, 5)) creates a 4x5 array
# with random integers between 1 (inclusive) and 11 (exclusive)
integer_random = np.random.randint(1, 11, size=(4, 5))

# Print the original random array
print(integer_random)

# Print a message to indicate the next operation
print("After deletion")

# Delete the second row (row index 1) from the array
# np.delete takes the array, index to delete, and axis=0 (rows)
updated_array = np.delete(integer_random, 1, axis=0)

# Print the updated array after deletion
print(updated_array)

[[10  7  8  1  7]
 [ 1 10  1  2  5]
 [ 2  8  1  9  9]
 [ 8  9  6  3  1]]
After deletion
[[10  7  8  1  7]
 [ 2  8  1  9  9]
 [ 8  9  6  3  1]]


In [54]:
# Generate a 4x5 array of random integers between 1 (inclusive) and 11 (exclusive)
integer_random = np.random.randint(1, 11, size=(4, 5))  

# Print the original random integer array
print(integer_random)

# Print a message indicating deletion will happen
print("After deletion")

# Delete the second column (index 1) from the array along axis=1 (columns)
updated_array = np.delete(integer_random, 1, axis=1)

# Print the updated array after the column deletion
print(updated_array)

[[ 4  5  7  5  7]
 [ 8  3  4  4  7]
 [ 3  1  5  5  7]
 [ 4  8  2  5 10]]
After deletion
[[ 4  7  5  7]
 [ 8  4  4  7]
 [ 3  5  5  7]
 [ 4  2  5 10]]
