## 1. Sorting NumPy Arrays
You can sort NumPy arrays of various types. Numeric arrays are sorted by
default in ascending order of numbers. On the other hand, text arrays are
sorted alphabetically.

### 1.1. Sorting Numeric Arrays
To sort an array in NumPy, you may call the np.sort() function and pass it to
your NumPy array.

In [3]:
import numpy as np

In [4]:
# Print a header to indicate the next array is unsorted
print("unsorted array")

# Create an array of 10 random integers between 1 and 20 (inclusive of 1, exclusive of 20)
my_array = np.random.randint(1, 20, 10)

# Print the randomly generated unsorted array
print(my_array)

# Print a header to indicate the next array will be sorted
print("\nsorted array")

# Sort the array in ascending order using NumPy's sort function
sorted_array = np.sort(my_array)

# Print the sorted array
print(sorted_array)

unsorted array
[14  7 19 15  8 11 12  5  8 13]

sorted array
[ 5  7  8  8 11 12 13 14 15 19]


### 1.2. Sorting Text Arrays
Text arrays are sorted in alphabetical order.

In [5]:
# Print a message indicating the start of the unsorted array
print("unsorted array")

# Create a NumPy array with four string elements (colors)
my_array = np.array(["Red", "Green", "Blue", "Yello"])

# Print the original (unsorted) array
print(my_array)

# Print a newline and a message indicating the start of the sorted array
print("\nsorted array")

# Sort the array in alphabetical order using np.sort() and store the result in sorted_array
sorted_array = np.sort(my_array)

# Print the sorted array
print(sorted_array)

unsorted array
['Red' 'Green' 'Blue' 'Yello']

sorted array
['Blue' 'Green' 'Red' 'Yello']


### 1.3. Sorting Boolean Arrays
Boolean arrays are sorted in a way that all the False values appear
first in an array.

In [6]:
# Print a header to indicate we are about to display the unsorted array
print("unsorted array")

# Create a NumPy array of boolean values
my_array = np.array([False, True, True, False, False, True, False, True])

# Print the original (unsorted) array
print(my_array)

# Print a header to indicate we are about to display the sorted array
print("\nSorted array")

# Sort the boolean array using NumPy's sort function
# Note: In NumPy, False is treated as 0 and True as 1 for sorting
sorted_array = np.sort(my_array)

# Print the sorted array (all False values will appear before True values)
print(sorted_array)

unsorted array
[False  True  True False False  True False  True]

Sorted array
[False False False False  True  True  True  True]


### 1.4. Sorting 2-D Arrays
In two-dimensional
arrays, each item itself is an array. The sort() function sorts an item in each
individual array in a two-dimensional array.

In [7]:
# Print a label to indicate that the next output is the unsorted array
print("unsorted array")

# Create a 4x6 NumPy array with random integers between 1 and 19 (inclusive)
# np.random.randint(low, high, size) generates random integers
my_array = np.random.randint(1, 20, size=(4, 6))

# Print the unsorted array
print(my_array)

# Print a label to indicate that the next output is the sorted array
print("\Sorted array")

# Sort each row of the array in ascending order
# np.sort sorts along the last axis by default (axis=-1), so rows are sorted individually
sorted_array = np.sort(my_array)

# Print the sorted array
print(sorted_array)

unsorted array
[[18  8 19  5 18 17]
 [ 9 17 19  1  2 11]
 [18  5 17 14  4  4]
 [ 6  3  6  5  7 15]]
\Sorted array
[[ 5  8 17 18 18 19]
 [ 1  2  9 11 17 19]
 [ 4  4  5 14 17 18]
 [ 3  5  6  6  7 15]]


### 1.5. Sorting in Descending Order
To do so, you can first sort an
array in ascending order via the sort() method. Next, you can pass the sorted
array to the flipud() method, which reverses the sorted array and returns the
array sorted in descending order.

In [8]:
# Print a heading for the unsorted array
print("unsorted array")

# Create an array of 10 random integers between 1 and 20 (inclusive)
my_array = np.random.randint(1, 20, 10)

# Print the unsorted array
print(my_array)

# Print a heading for the sorted array
print("\nsorted array")

# Sort the array in ascending order using np.sort()
sorted_array = np.sort(my_array)

# Reverse the sorted array to get descending order using np.flipud()
reverse_sorted = np.flipud(sorted_array)

# Print the reversed (descending) sorted array
print(reverse_sorted)

unsorted array
[ 4 14 18  6  9 18 12  8  9 16]

sorted array
[18 18 16 14 12  9  9  8  6  4]


## 2. Reshaping NumPy Arrays
To do so, you can use the
reshape() method and pass it the new shape for your NumPy array.

### 2.1. Reshaping from Lower to Higher Dimensions

In [9]:
# Print a title for the one-dimensional array section
print("one-dimensional array")

# Create a one-dimensional array with 10 random integers between 1 and 19 (inclusive)
one_d_array = np.random.randint(1, 20, 10)

# Print the generated one-dimensional array
print(one_d_array)

# Print a title for the two-dimensional array section
print("\ntwo-dimensional array")

# Reshape the one-dimensional array into a two-dimensional array with 2 rows and 5 columns
two_d_array = one_d_array.reshape(2, 5)

# Print the reshaped two-dimensional array
print(two_d_array)

one-dimensional array
[18  9  5 10 11  7 14  3 12 13]

two-dimensional array
[[18  9  5 10 11]
 [ 7 14  3 12 13]]


In [10]:
# Print a header to indicate we are creating a one-dimensional array
print("one-dimensional array")

# Create a one-dimensional NumPy array with 10 random integers between 1 and 19 (inclusive)
one_d_array = np.random.randint(1, 20, 10)

# Print the generated one-dimensional array
print(one_d_array)

# Print a header to indicate we are creating a two-dimensional array
print("\ntwo-dimensional array")

# Reshape the one-dimensional array into a two-dimensional array with 2 rows and 5 columns
two_d_array = np.reshape(one_d_array, (2, 5))

# Print the reshaped two-dimensional array
print(two_d_array)

one-dimensional array
[11  1 13  4 15  6 12 11 19 19]

two-dimensional array
[[11  1 13  4 15]
 [ 6 12 11 19 19]]


In [11]:
# Print heading for two-dimensional array
print("two-dimensional array")

# Create a 2D array (4 rows, 6 columns) with random integers between 1 and 19
two_d_array = np.random.randint(1, 20, size=(4, 6))

# Print the generated 2D array
print(two_d_array)

# Print heading for three-dimensional array
print("\nthree-dimensional array")

# Reshape the 2D array into a 3D array with shape (3, 4, 2)
three_d_array = np.reshape(two_d_array, (3, 4, 2))

# Print the generated 3D array
print(three_d_array)

two-dimensional array
[[19 13  6 12  7  2]
 [14 16 13 18  6 18]
 [ 2 11 19  9 14 17]
 [ 6 12 12  1  2 13]]

three-dimensional array
[[[19 13]
  [ 6 12]
  [ 7  2]
  [14 16]]

 [[13 18]
  [ 6 18]
  [ 2 11]
  [19  9]]

 [[14 17]
  [ 6 12]
  [12  1]
  [ 2 13]]]


In [13]:
# Print heading for two-dimensional array
print("two-dimensional array")

# Create a 2D array (4 rows, 6 columns) with random integers from 1 to 19
two_d_array = np.random.randint(1, 20, size=(4, 6))

# Print the two-dimensional array
print(two_d_array)

# Print heading for three-dimensional array
print("\nthree-dimensional array")

# Reshape the 2D array into a 3D array with shape (1, 4, 6)
# Here, 1 is the number of "blocks", 4 is rows, and 6 is columns
three_d_array = np.reshape(two_d_array, (1, 4, 2))

# Print the three-dimensional array
print(three_d_array)

two-dimensional array
[[ 4  5 12 11  8  3]
 [ 5  8  3  5  8 10]
 [11  8  6 14 11  4]
 [ 1 16 17 15  1 10]]

three-dimensional array


ValueError: cannot reshape array of size 24 into shape (1,4,2)

### 2.2. Reshaping from Higher to Lower Dimensions

In [15]:
# Print a label for clarity
print("two-dimensional array")

# Create a 2D NumPy array with random integers between 1 and 19 (inclusive)
# The array has shape (4, 6) meaning 4 rows and 6 columns
two_d_array = np.random.randint(1, 20, size=(4, 6))

# Print the generated 2D array
print(two_d_array)

# Print a label for clarity
print("\none-dimensional array")

# Reshape the 2D array into a 1D array with 24 elements (4 * 6 = 24)
# This flattens the array from 2D to 1D
one_d_array = two_d_array.reshape(24)

# Print the reshaped 1D array
print(one_d_array)

two-dimensional array
[[17 10  3 19 18  3]
 [ 2  3  6  7 13 14]
 [ 9  6  9 17  4  1]
 [15  7 16 12 12 17]]

one-dimensional array
[17 10  3 19 18  3  2  3  6  7 13 14  9  6  9 17  4  1 15  7 16 12 12 17]


In [16]:
# Print a header to indicate the start of working with a two-dimensional array
print("two-dimensional array")

# Create a 2D NumPy array with random integers between 1 and 19 (inclusive)
# The array shape is (4, 6), meaning 4 rows and 6 columns
two_d_array = np.random.randint(1, 20, size=(4, 6))

# Print the generated 2D array
print(two_d_array)

# Print a header to indicate the start of working with a one-dimensional array
print("\none-dimensional array")

# Reshape the 2D array into a 1D array (flatten it)
# The -1 tells NumPy to calculate the size of the new dimension automatically
one_d_array = two_d_array.reshape(-1)

# Print the flattened 1D array
print(one_d_array)

two-dimensional array
[[17  9  5 12  5 15]
 [ 3  5  2  6  9  5]
 [ 1 19  1  6  5  1]
 [ 5  4 10 14 15  4]]

one-dimensional array
[17  9  5 12  5 15  3  5  2  6  9  5  1 19  1  6  5  1  5  4 10 14 15  4]


In [17]:
# Print a header to indicate we're working with a two-dimensional array
print("two-dimensional array")

# Create a 3D NumPy array with random integers between 1 and 19 (inclusive)
# The shape of the array is (4, 2, 6): 4 blocks, each with 2 rows and 6 columns
three_d_array = np.random.randint(1, 20, size=(4, 2, 6))

# Print the generated 3D array
print(three_d_array)

# Print a header to indicate we're working with a one-dimensional array
print("\non-dimensional array")

# Reshape the 3D array into a 1D array (flatten it)
# The -1 tells NumPy to calculate the correct size automatically
one_d_array = three_d_array.reshape(-1)

# Print the flattened 1D array
print(one_d_array)

two-dimensional array
[[[ 5  3  5  7  7 16]
  [15 13  7  1  4 13]]

 [[17  8 14  1  9 19]
  [ 8  5 10  2 10  2]]

 [[16 17 17  9  2 16]
  [ 7 18 15  6  4  6]]

 [[ 9  9 15  4 18 10]
  [ 4  5  6  9 10  6]]]

on-dimensional array
[ 5  3  5  7  7 16 15 13  7  1  4 13 17  8 14  1  9 19  8  5 10  2 10  2
 16 17 17  9  2 16  7 18 15  6  4  6  9  9 15  4 18 10  4  5  6  9 10  6]


## 3. Indexing and Slicing NumPy Arrays
NumPy arrays can be indexed and sliced. Slicing an array means dividing an
array into multiple parts.
NumPy arrays are indexed just like normal lists. Indexes in NumPy arrays
start from 0, which means that the first item of a NumPy array is stored at the
0th index.

In [18]:
# Create a NumPy array of integers from 1 to 10 (inclusive)
s = np.arange(1, 11)

# Print the array to the console
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# Print the second element of the numpy array (or sequence) `s`
print(s[1])

2


In [20]:
# Print elements from index 1 (inclusive) to index 9 (exclusive) of the NumPy array `s`
print(s[1:9])

[2 3 4 5 6 7 8 9]


In [21]:
# Print the first 5 elements of the array or Series 's' (index 0 to 4)
print(s[:5])

# Print all elements of 's' starting from index 5 to the end
print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [22]:
# Define three rows as Python lists
row1 = [10, 12, 13]  # First row with three elements
row2 = [45, 32, 16]  # Second row with three elements
row3 = [45, 32, 16]  # Third row (same as row2)

# Create a 2D NumPy array (matrix) from the three rows
nums_2d = np.array([row1, row2, row3])

# Print a slice of the 2D array:
# nums_2d[:2, :] selects:
#   - the first two rows (index 0 and 1) [:2]
#   - all columns [:]
print(nums_2d[:2, :])  # Output: first two rows of the array

[[10 12 13]
 [45 32 16]]


In [23]:
# Define three rows as Python lists
row1 = [10, 12, 13]   # First row of numbers
row2 = [45, 32, 16]   # Second row of numbers
row3 = [45, 32, 16]   # Third row of numbers (same as row2 here)

# Create a 2D NumPy array from the three rows
nums_2d = np.array([row1, row2, row3])  # Shape will be (3, 3)

# Print all rows but only the first two columns
# nums_2d[:, :2] means:
#   ':'   => select all rows
#   ':2'  => select columns from index 0 up to (but not including) index 2
print(nums_2d[:, :2])  # Output will be a (3, 2) array

[[10 12]
 [45 32]
 [45 32]]


In [24]:
# Define three rows as Python lists
row1 = [10, 12, 13]  # First row with 3 elements
row2 = [45, 32, 16]  # Second row with 3 elements
row3 = [45, 32, 16]  # Third row (same as row2)

# Create a 2D NumPy array from the three rows
nums_2d = np.array([row1, row2, row3])

# Print a sliced portion of the 2D array
# Slice rows starting from index 1 (2nd row) to the end
# and columns starting from index 1 (2nd column) to the end
print(nums_2d[1:, 1:])

[[32 16]
 [32 16]]


## 4. Broadcasting NumPy Arrays
Broadcasting allows you to perform various operations between NumPy
arrays of different shapes.

In [25]:
# Create a NumPy array named 'array1' with three integer elements
array1 = np.array([14, 25, 31])

# Create a NumPy array named 'array2' with a single integer element
array2 = np.array([10])

# Add 'array2' to 'array1' using NumPy's broadcasting feature
# Broadcasting automatically expands 'array2' to match the shape of 'array1'
# So 10 is added to each element of 'array1'
result = array1 + array2

# Print the resulting array
print(result)  # Output: [24 35 41]

[24 35 41]


In [26]:
# Create a 3x4 array with random integers from 1 to 19 (inclusive)
array1 = np.random.randint(1, 20, size=(3, 4))
print(array1)  # Print the generated 3x4 array

# Create a 1-element array containing the value 10
array2 = np.array([10])
print("after broadcasting")  # Print a message indicating the next step

# Add array1 and array2 together using broadcasting
# Here, numpy automatically "broadcasts" array2 (shape (1,)) to match array1's shape (3, 4)
result = array1 + array2

# Print the resulting array after broadcasting addition
print(result)

[[10 10  1  1]
 [ 6  6 10 15]
 [ 3 10 19  9]]
after broadcasting
[[20 20 11 11]
 [16 16 20 25]
 [13 20 29 19]]


In [27]:
# Create a 3x4 array of random integers between 1 and 20 (inclusive of 1, exclusive of 20)
# Shape of array1: 3 rows and 4 columns
array1 = np.random.randint(1, 20, size=(3, 4))
print(array1)  # Print the randomly generated 3x4 array

# Create a 1D NumPy array with 4 elements
# Shape of array2: (4,)
array2 = np.array([5, 10, 20, 25])

# Print message to indicate broadcasting is about to happen
print("after broadcasting")

# Add array2 to each row of array1 using NumPy broadcasting
# Broadcasting automatically expands array2 to match array1's shape (3x4)
result = array1 + array2

# Print the result of the element-wise addition
print(result)

[[16  4  4  1]
 [ 4 13  1  9]
 [12 15  3 17]]
after broadcasting
[[21 14 24 26]
 [ 9 23 21 34]
 [17 25 23 42]]


In [28]:
# Create a 3x4 array with random integers between 1 (inclusive) and 20 (exclusive)
array1 = np.random.randint(1, 20, size=(3, 4))
print(array1)  # Print the generated 3x4 array

# Create a 3x1 array manually
array2 = np.array([[5],    # First row element is 5
                   [10],   # Second row element is 10
                   [20]])  # Third row element is 20
print("after broadcasting")

# Add array1 and array2 together using broadcasting
# Broadcasting automatically expands array2's shape (3x1) to match array1's shape (3x4)
# Each row of array1 is added with the corresponding scalar from array2
result = array1 + array2
print(result)  # Print the resulting array after broadcasting and addition

[[15 10  8 15]
 [12  8 18  8]
 [ 2  7 16  8]]
after broadcasting
[[20 15 13 20]
 [22 18 28 18]
 [22 27 36 28]]


## 5. Copying NumPy Arrays
There are two main ways to copy an array in NumPy. You can either copy
the contents of the original array, or you can copy the reference to the
original array into another array.
To copy the contents of the original array into a new array, you can call the
copy() function on the original array. Now, if you modify the contents of the
new array, the contents of the original array are not modified.

In [29]:
# Create a NumPy array with values [10, 12, 14, 16, 18, 20]
array1 = np.array([10, 12, 14, 16, 18, 20])

# Create a copy of array1 and assign it to array2
# This ensures array2 is an independent copy and changes to it won't affect array1
array2 = array1.copy()

# Modify the second element (index 1) of array2 to be 20
array2[1] = 20

# Print the original array1 to show it remains unchanged
print(array1)  # Output: [10 12 14 16 18 20]

# Print array2 to show the change at index 1
print(array2)  # Output: [10 20 14 16 18 20]

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [30]:
# Create a NumPy array called array1 with the given elements
array1 = np.array([10, 12, 14, 16, 18, 20])

# Create a view (shallow copy) of array1 and assign it to array2
# array2 shares the same data buffer as array1
array2 = array1.view()

# Modify the second element (index 1) of array2
# This change also affects array1 because array2 is a view of array1
array2[1] = 20

# Print array1 to show that it reflects the change made via array2
print(array1)  # Output: [10 20 14 16 18 20]

# Print array2 to show its current contents
print(array2)  # Output: [10 20 14 16 18 20]

[10 20 14 16 18 20]
[10 20 14 16 18 20]


## 6. NumPy I/O Operations
You can save and load NumPy arrays to and from your local drive.

### 6.1. Saving a NumPy Array
To save a NumPy array, you need to call the save() method from the NumPy
module and pass it the file name for your NumPy as the first argument, while
the array object itself as the second argument.

In [31]:
# Create a NumPy array with the given list of integers
array1 = np.array([10, 12, 14, 16, 18, 20])

# Save the NumPy array to a binary file named 'my_array.npy' in the specified directory
# The file will be created at C:\temp\ with the name 'my_array.npy'
np.save("c:\\temp\\my_array", array1)

In [32]:
# Create a NumPy array with the specified elements
array1 = np.array([10, 12, 14, 16, 18, 20])

# Save the NumPy array 'array1' to a text file at the specified path
# Each element of the array will be written on a separate line in the file
np.savetxt("c:\\temp\\my_array.txt", array1)

### 6.2. Loading a NumPy Array
To load a NumPy array in the “NPY” format, you can use the load() method

In [33]:
# Load a NumPy array from a .npy file located at "C:\temp\my_array.npy"
# The np.load() function reads the binary file and reconstructs the array
loaded_array = np.load("c:\\temp\\my_array.npy")  # Note: use double backslashes in file paths on Windows

# Print the contents of the loaded NumPy array to the console
print(loaded_array)

[10 12 14 16 18 20]


In [34]:
# Load data from a text file located at "c:\temp\my_array.txt"
# np.loadtxt reads the text file and returns its contents as a NumPy array
# Make sure the file exists and contains numeric data, otherwise it will raise an error
loaded_array = np.loadtxt("c:\\temp\\my_array.txt")  # Use double backslashes or raw string for Windows path

# Print the contents of the loaded NumPy array to the console
print(loaded_array)

[10. 12. 14. 16. 18. 20.]
